config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'application#hello_world'

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :posts
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  # TODO: fix this!
  delete 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :title, presence: true
  validates :description, presence: true, length: { maximum: 120 }
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true
  
  has_many :posts, dependent: :destroy
  
  has_many :follower_relationships, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  has_many :followed_relationships, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy
  
  has_many :following, through: :follower_relationships, source: :followed
  has_many :followers, through: :followed_relationships, source: :follower
  has_secure_password
  
  # follows a user
  def follow(other_user)
    following << other_user
  end
  
  # unfollows a user
  def unfollow(other_user)
    following.delete(other_user)
  end
  
  # returns true if the current user is following the other user
  def following?(other_user)
    following.include?(other_user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  def hello_world
    if logged_in?
      redirect_to users_path
    else
      redirect_to login_path
    end
  end

  def check_user
    redirect_to login_path unless logged_in?
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :check_user, only: [ :create ]

  def index
    @posts = Post.all
  end
  
  def show
    @post = Post.where(id: params[:id]).first
  end
  
  def create
    @post = current_user.posts.new(post_params)

    if @post.save
      redirect_to user_path(current_user)
    else
      @user = current_user
      @posts = @user.posts.paginate(page: params[:page], per_page: 5)
      render 'users/show', status: 422
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to user_path(current_user)
    else
      render 'posts/edit', status: 422
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :description)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params['email'])
    if user.present? && user.authenticate(params['password'])
      log_in(user)
      redirect_to user_path(user)
    else
      flash.now[:error] = 'Invalid credentials'
      render :new
    end
  end

  def destroy
    log_out
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_user, only: [ :index, :show, :destroy ]
  before_action :admin_user, only: [ :destroy ]

  def index
    @users = User.all
  end

  def show
    @user = User.where(id: params[:id]).first
    if @user.present?
      @posts = @user.posts.paginate(page: params[:page], per_page: 5)
      @post = Post.new
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to user_path(@user)
    else
      render 'users/new'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to '/users'
  end
  
  def following
    @title = 'Following'
    @user = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow'
  end
  
  def followers
    @title = 'Followers'
    @user = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    session[:user_id] = nil
  end

  def current_user
    if session[:user_id].present?
      User.find_by(id: session[:user_id])
    end
  end
  
  # return true if the given user is the current user
  def current_user?(user)
    current_user == user
  end
  
  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/alta_ruta.html.erb
Alta ruta mai smechera

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Twitter</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <%= link_to 'Users', '/users', class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Posts', '/posts', class: 'nav-link' %>
            </li>
          </ul>

          <% if logged_in? %>
            <div class="navbar-nav pull-right">
              <%= link_to 'Logout', logout_path, data:{turbo_method: :delete}, class: 'nav-link btn btn-link' %>
            </div>
            <div class="navbar-nav pull-right">
              <%= current_user.name %>
            </div>
          <% else %>
            <div class="navbar-nav pull-right">
              <%= link_to 'Sign Up', new_user_path, class: 'nav-link' %>
            </div>
            <div class="navbar-nav pull-right">
              <%= link_to 'Login', login_path, class: 'nav-link' %>
            </div>
          <% end %>
        </div>
      </div>
    </nav>

    <div class="p-2">
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_post.html.erb
<div class="card user-card">
  <div class="card-body">
    <h5 class="card-title"><%= link_to(post.title, post) %></h5>
    <p class="card-text">
      description: <%= post.description %><br>
      Posted by <%= link_to post.user.name, post.user %> <%= time_ago_in_words(post.updated_at) %> ago.
    </p>
    <%= link_to 'Edit', edit_post_path(post) %>
  </div>
</div>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render partial: 'shared/error_messages', locals: { obj: @post } %>
<%= form_with model: @post do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, class: 'form-control', placeholder: 'Insert title...' %>

  <%= f.label :description %>
  <%= f.text_field :description, class: 'form-control', placeholder: 'Insert content...' %>

  <%= f.submit 'Edit', class: 'btn btn-primary mt-2' %>
<% end %>

app/views/posts/index.html.erb
<h1> Post </h1>

<ul>
    <% @posts.each do |post| %>
        <li>
            <%= render post %>
        </li>
    <% end %>
</ul>

app/views/posts/show.html.erb
<div>
  <%= link_to('Back to posts', '/posts') %>
</div>

<% if @post.nil? %>
    Nu exista postarea ceruta.
<% else %>
    <%= render @post %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if obj.errors.present? %>
  <div class="alert alert-danger">
    <% obj.errors.full_messages.each do |error| %>
      <div>
        <%= error %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/shared/_stats.html.erb
<div class='row'>
  <div class="col-md-6 col-lg-3 col-sm-6 border-right text-center">
    <a href="<%= following_user_path(@user) %>">
      <strong><%= @user.following.count %></strong><br>
      <strong>Following</strong>
    </a>
  </div>
  <div class="col-md-6 col-lg-3 col-sm-6 border-right text-center">
    <a href="<%= followers_user_path(@user) %>">
      <strong><%= @user.followers.count %></strong><br>
      <strong>Followers</strong>
    </a>
  </div>
</div>

app/views/users/_user.html.erb
<div class="card user-card">
  <div class="card-body">
    <h5 class="card-title"><%= link_to(user.name, "/users/#{user.id}") %></h5>
    <p class="card-text">
      email: <%= user.email %><br>
      age: <%= user.age %><br>
      gender: <%= user.gender %>
    </p>
    <%# TO DO make sure confirmation message works %>
    <% if current_user.admin? && !current_user?(user) %>
      <%= link_to 'delete', user, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<h1> Users </h1>

<ul>
    <% @users.each do |user| %>
        <li>
            <%= render user %>
        </li>
    <% end %>
</ul>

<%
=begin%>
  <%= render partial: 'user', locals: { user: user } %>
  <%  %> - doar ruleaza cod de ruby
  <%= %> - afiseaza codul de ruby
<%
=end%>

app/views/users/new.html.erb
<% if flash[:error] %>
  <div class="error"><%= flash[:error] %></div>
<% end %>

<div class="row justify-content-center">
  <div class="col-xs-12 col-sm-5">
    <%= render partial: 'shared/error_messages', locals: { obj: @user } %>

    <%= form_for @user do |f| %>
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %><br />

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %><br />

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %><br />

      <%= f.submit 'Sign Up' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div>
  <%= link_to('Back to users', '/users') %>
</div>


<div class="row">
  <div class="col-md-4">
    <% if @user.nil? %>
        Nu exista userul cerut.
    <% else %>
        <%= render @user %>
        <%= render 'shared/stats'%>
        <% if current_user?(@user) %>
          <div class="p-2">
            <%= render partial: 'shared/error_messages', locals: { obj: @post } %>
            <%= form_with model: @post do |f| %>
              <%= f.label :title %>
              <%= f.text_field :title, class: 'form-control', placeholder: 'Insert title...' %>

              <%= f.label :description %>
              <%= f.text_field :description, class: 'form-control', placeholder: 'Insert content...' %>

              <%= f.submit 'Post', class: 'btn btn-primary mt-2' %>
            <% end %>
          </div>
        <% end %>
    <% end %>
  </div>
  <% if @user.present? %>
    <div class="col-md-6">
      <h3> Posts (<%= @posts.count%>)</h3>
      <%= render @posts %>
      <%= will_paginate(@posts, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer, class: "pagination bg-transparent") %>
    </div>
  <% end %>
</div>

app/views/users/show_follow.html.erb
<div>
  <%= link_to('Back to users', '/users') %>
</div>


<div class="row">
  <div class="col-md-4">
    <% if @user.nil? %>
        Nu exista userul cerut.
    <% else %>
        <%= render @user %>
    <% end %>
  </div>
  <% if @user.present? %>
    <div class="col-md-6">
      <h3> <%= @title %></h3>
      <%= render @users %>
      <%= will_paginate(@users, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer, class: "pagination bg-transparent") %>
    </div>
  <% end %>
</div>